#!/usr/bin/env python3
"""Generate _redirects and check it against the redirect stubs.

The stubs (root *.html files containing http-equiv="refresh") are the source of
truth for retired URLs. This emits the Cloudflare Workers static assets / Pages
_redirects format:

  * both the .html and the extensionless form of every retired URL -> target.html
  * extensionless alias -> .html for every live page (with html_handling = "none"
    in wrangler.jsonc, Cloudflare then serves the .html canonicals directly and
    301s everything else; no 307 -> 301 -> 307 chains)

GitHub Pages ignores this file entirely. It exists so a DNS move to Cloudflare
gives real 301s from day one. Run from the repo root:
    python3 scripts/gen_redirects.py
"""
import glob
import re
import sys

REFRESH_RE = re.compile(r'content="0;url=([^"]+)"')
LIMIT = 2000  # Cloudflare static redirect rule limit


def read(path):
    return open(path, encoding="utf-8", errors="ignore").read()


def main():
    stubs, live = {}, []
    for f in sorted(glob.glob("*.html")):
        src = read(f)
        m = REFRESH_RE.search(src) if 'http-equiv="refresh"' in src else None
        if m:
            t = m.group(1)
            if not t.startswith("/"):
                t = "/" + t
            if not t.endswith(".html"):
                t += ".html"
            stubs[f] = t
        elif f not in ("404.html", "index.html"):
            live.append(f)
    for f in sorted(glob.glob("blog/*.html")):
        if f != "blog/index.html":
            live.append(f)

    bad = sorted({t for t in stubs.values() if not glob.glob(t.lstrip("/"))})
    if bad:
        print("ERROR: targets missing:", bad[:10])
        sys.exit(1)

    lines = []
    for f, t in stubs.items():
        slug = "/" + f[:-5]
        lines.append(f"{slug}.html\t{t}\t301")
        lines.append(f"{slug}\t{t}\t301")
    for f in live:
        slug = "/" + f[:-5]
        lines.append(f"{slug}\t{slug}.html\t301")
    lines.append("/index.html\t/\t301")
    lines.append("/blog\t/blog/index.html\t301")
    lines.append("/blog/\t/blog/index.html\t301")

    if len(lines) > LIMIT:
        print(f"ERROR: {len(lines)} rules exceed the {LIMIT} static redirect limit")
        sys.exit(1)
    header = (
        "# Generated by scripts/gen_redirects.py from the redirect stubs. "
        "Honored by Cloudflare (Workers static assets / Pages), ignored by GitHub Pages.\n"
    )
    open("_redirects", "w", encoding="utf-8").write(header + "\n".join(lines) + "\n")
    print(f"{len(stubs)} stubs, {len(live)} live pages, {len(lines)} rules")


if __name__ == "__main__":
    main()
